services:
  orders_database:
    image: postgres:latest
    env_file: ./order_service_database/order_service_database.env
    command: [ "postgres", "-c", "wal_level=logical" ]
    ports:
      - "1000:5432"
    networks:
      default:
        ipv4_address: 192.168.1.5
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U $$POSTGRES_USER"]

  order:
    image: nawaphon2539/microservices-lab:transactional_outbox_pattern.transaction_log_tailing.order_service
    env_file: ./order_service/order_service.env
    ports:
      - "1002:8080"
    networks:
      default:
        ipv4_address: 192.168.1.7
    depends_on:
      orders_database:
        condition: service_healthy
    healthcheck:
      test: ["CMD", "java", "-jar", "heart_beat-0.0.1.jar"]

  zookeeper:
    image: ubuntu/zookeeper:latest
    env_file: ./zookeeper/zookeeper.env
    networks:
      default:
        ipv4_address: 192.168.1.2

  kafka:
    image: ubuntu/kafka:latest
    command: [ "/etc/kafka/server.properties", "--override", "advertised.listeners=PLAINTEXT://kafka:9092" ]
    env_file: ./kafka/kafka.env
    ports:
      - "9092:9092"
    networks:
      default:
        ipv4_address: 192.168.1.3
    depends_on: [ zookeeper ]

  debezium:
    image: quay.io/debezium/connect:latest
    env_file: ./debezium/order_service_debezium.env
    ports:
      - '8083:8083'
    networks:
      default:
        ipv4_address: 192.168.1.4
    depends_on: [ kafka ]


networks:
  default:
    ipam:
      config:
        - subnet: 192.168.1.0/28
          gateway: 192.168.1.1
